//! 剪贴板：只读文本，认「隐蔽 / 瞬时」标记，识别自己写入的那一次。

use objc2_app_kit::{NSPasteboard, NSPasteboardTypeString};
use objc2_foundation::NSString;

/// 密码管理器与系统在放敏感内容时打的标记（nspasteboard.org 约定），见到任何一个都不读。
const SECRET_TYPES: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
    "de.petermaurer.TransientPasteboardType",
];

/// 一次新复制。
pub struct Copied {
    pub text: String,

    /// 带了隐蔽 / 瞬时标记。
    pub concealed: bool,

    /// 短时间内连着复制了同一段文字（连按两次 ⌘C）：用户在要求重新来一遍。
    pub repeat: bool,
}

pub struct ClipboardWatch {
    /// 上次看到的 changeCount。
    seen: isize,

    /// 自己写入剪贴板后的 changeCount，不当成用户复制。
    own: Option<isize>,

    /// 上一次复制的文字与时间，认连按两次。
    last: Option<(String, std::time::Instant)>,
}

/// 两次复制间隔不超过这么久、文字相同，算连按。
const REPEAT_WINDOW: std::time::Duration = std::time::Duration::from_millis(1200);

impl ClipboardWatch {
    /// 以当前剪贴板为起点：启动前已经复制的内容不处理。
    pub fn new() -> Self {
        Self {
            seen: NSPasteboard::generalPasteboard().changeCount(),
            own: None,
            last: None,
        }
    }

    /// 重新以当前为起点，激活输入法时调：之前复制的东西不追溯。
    pub fn reset(&mut self) {
        self.seen = NSPasteboard::generalPasteboard().changeCount();
    }

    /// 有新复制就返回它的文本；没变化或不是文本返回 `None`。
    pub fn poll(&mut self) -> Option<Copied> {
        let pasteboard = NSPasteboard::generalPasteboard();
        let count = pasteboard.changeCount();
        if count == self.seen {
            return None;
        }
        // 一次轮询间隔里复制了两次以上，changeCount 会一下跳好几格
        let jumped = count - self.seen >= 2;
        self.seen = count;
        if self.own == Some(count) {
            return None;
        }
        let concealed = pasteboard.types().is_some_and(|types| {
            types
                .iter()
                .any(|kind| SECRET_TYPES.contains(&kind.to_string().as_str()))
        });
        if concealed {
            // 隐蔽内容连文本都不读
            return Some(Copied {
                text: String::new(),
                concealed: true,
                repeat: false,
            });
        }
        // SAFETY: 只读 AppKit 导出的类型名常量
        let text = unsafe { pasteboard.stringForType(NSPasteboardTypeString) }?.to_string();
        let again = self
            .last
            .as_ref()
            .is_some_and(|(previous, at)| *previous == text && at.elapsed() < REPEAT_WINDOW);
        self.last = Some((text.clone(), std::time::Instant::now()));
        Some(Copied {
            text,
            concealed: false,
            repeat: jumped || again,
        })
    }
}

/// 现在剪贴板里的文本，不管是不是新复制的；带隐蔽标记或不是文本返回 `None`。
pub fn read_now() -> Option<String> {
    let pasteboard = NSPasteboard::generalPasteboard();
    let concealed = pasteboard.types().is_some_and(|types| {
        types
            .iter()
            .any(|kind| SECRET_TYPES.contains(&kind.to_string().as_str()))
    });
    if concealed {
        return None;
    }
    // SAFETY: 只读 AppKit 导出的类型名常量
    unsafe { pasteboard.stringForType(NSPasteboardTypeString) }.map(|text| text.to_string())
}

/// 把文本写进剪贴板，并返回写入后的 changeCount，供 [`ClipboardWatch`] 认出这是自己写的。
pub fn write(text: &str) -> isize {
    let pasteboard = NSPasteboard::generalPasteboard();
    pasteboard.clearContents();
    // SAFETY: 只读 AppKit 导出的类型名常量
    unsafe {
        pasteboard.setString_forType(&NSString::from_str(text), NSPasteboardTypeString);
    }
    pasteboard.changeCount()
}

impl ClipboardWatch {
    /// 记下自己写入的那一次。
    pub fn mark_own(&mut self, count: isize) {
        self.own = Some(count);
        self.seen = count;
    }
}
